import type { CollectedEvent } from "../types";

export const designConferenceSeeds: CollectedEvent[] = [
  {
    source: "conf-design",
    externalId: "design-spectrum-2026",
    title: "Design Spectrum Conference 2026",
    category: "DESIGN",
    type: "CONFERENCE",
    startDate: "2026-09-19T10:00:00",
    endDate: "2026-09-19T18:00:00",
    organizer: "디자인 스펙트럼",
    location: "신라스테이 광화문",
    isOnline: false,
    fee: 80000,
    link: "https://designspectrum.org",
    description:
      "프로덕트 디자이너 커뮤니티 디자인 스펙트럼의 연례 컨퍼런스. UX, 시스템, 리서치 트랙.",
  },
  {
    source: "conf-design",
    externalId: "uxkonf-2026",
    title: "UX KOREA Annual Conference 2026",
    category: "DESIGN",
    type: "CONFERENCE",
    startDate: "2026-11-06T10:00:00",
    endDate: "2026-11-06T18:00:00",
    organizer: "UX Korea",
    location: "서울 코엑스",
    isOnline: false,
    fee: 150000,
    link: "https://uxkorea.org",
    description:
      "UX 실무자·리서처 대상 컨퍼런스. 서비스 디자인, 리서치 방법론, AI/UX 통합 등.",
  },
  {
    source: "conf-design",
    externalId: "toss-design-conf-2026",
    title: "Simplicity 26 — 토스 디자인 컨퍼런스",
    category: "DESIGN",
    type: "CONFERENCE",
    startDate: "2026-10-08T13:00:00",
    endDate: "2026-10-08T18:00:00",
    organizer: "토스 (Viva Republica)",
    location: "강남 SETEC",
    isOnline: false,
    fee: 0,
    link: "https://toss.im/simplicity",
    description:
      "토스가 주최하는 프로덕트 디자인 컨퍼런스. 단순함을 둘러싼 의사결정 사례 중심.",
  },
  {
    source: "conf-design",
    externalId: "fitc-seoul-2026",
    title: "FITC Seoul 2026",
    category: "DESIGN",
    type: "CONFERENCE",
    startDate: "2026-06-26T10:00:00",
    endDate: "2026-06-27T18:00:00",
    organizer: "FITC",
    location: "동대문디자인플라자 (DDP)",
    isOnline: false,
    fee: 250000,
    link: "https://fitc.ca/event/seoul26",
    description:
      "디자인·모션·인터랙티브 분야 글로벌 컨퍼런스의 서울 에디션.",
  },
];
