import type { CollectedEvent } from "../types";

export const financeConferenceSeeds: CollectedEvent[] = [
  {
    source: "conf-finance",
    externalId: "korea-fintech-week-2026",
    title: "Korea Fintech Week 2026",
    category: "FINANCE",
    type: "CONFERENCE",
    startDate: "2026-08-26T10:00:00",
    endDate: "2026-08-28T18:00:00",
    organizer: "금융위원회·한국핀테크지원센터",
    location: "동대문디자인플라자 (DDP)",
    isOnline: false,
    fee: 0,
    link: "https://fintechweek.or.kr",
    description:
      "국내 최대 핀테크 컨퍼런스. 정책, 가상자산, 임베디드 금융, 채용 부스 운영.",
  },
  {
    source: "conf-finance",
    externalId: "kca-investment-forum-2026",
    title: "한국재무학회 투자전략 포럼 2026",
    category: "FINANCE",
    type: "CONFERENCE",
    startDate: "2026-10-23T13:00:00",
    endDate: "2026-10-23T18:00:00",
    organizer: "한국재무학회",
    location: "여의도 콘래드 서울",
    isOnline: false,
    fee: 50000,
    link: "https://www.kafa.or.kr",
    description:
      "자산운용·리서치·증권사 실무자 대상 투자전략 포럼.",
  },
  {
    source: "conf-finance",
    externalId: "investment-asset-manager-2026",
    title: "투자자산운용사 자격시험 (2026 정기)",
    category: "FINANCE",
    type: "CERTIFICATION",
    startDate: "2026-06-07T10:00:00",
    endDate: "2026-06-07T13:00:00",
    registrationStart: "2026-04-27T09:00:00",
    registrationEnd: "2026-05-06T17:00:00",
    organizer: "금융투자협회",
    location: "전국 시험장",
    isOnline: false,
    fee: 55000,
    link: "https://www.kofia.or.kr",
    description: "자산운용 업무 종사자/지망생을 위한 금융자격시험.",
  },
];
