import type { CollectedEvent } from "../types";

// 한국에서 매년 정기적으로 열리는 주요 IT 컨퍼런스 시드.
// 정확한 날짜는 매년 주최사가 공지하면 갱신해야 한다 — 여기 적힌 날짜는
// 과거 패턴(개최 월/요일)과 공식 공지를 토대로 한 잠정 일정이다.
// Why: feconf.kr·deview.kr 등은 RSS/공개 API가 없어 매뉴얼 큐레이션이 가장 빠름.

export const itConferenceSeeds: CollectedEvent[] = [
  {
    source: "conf-it",
    externalId: "feconf-2026",
    title: "FEConf 2026",
    category: "IT",
    type: "CONFERENCE",
    startDate: "2026-10-24T09:30:00",
    endDate: "2026-10-24T18:00:00",
    organizer: "FEConf 운영위원회",
    location: "삼성동 코엑스",
    isOnline: false,
    fee: 30000,
    link: "https://feconf.kr",
    description:
      "프론트엔드 개발자를 위한 국내 최대 규모 컨퍼런스. React, Vue, 웹 표준, 성능, DX 등 다양한 트랙.",
  },
  {
    source: "conf-it",
    externalId: "infcon-2026",
    title: "INFCON 2026",
    category: "IT",
    type: "CONFERENCE",
    startDate: "2026-08-29T10:00:00",
    endDate: "2026-08-29T18:00:00",
    organizer: "인프런",
    location: "코엑스",
    isOnline: false,
    fee: 50000,
    link: "https://www.inflearn.com/conf/infcon",
    description:
      "인프런이 주최하는 개발자·디자이너 합동 컨퍼런스. 커리어/기술/협업을 아우르는 트랙 구성.",
  },
  {
    source: "conf-it",
    externalId: "ifkakao-2026",
    title: "if(kakao) 2026",
    category: "IT",
    type: "CONFERENCE",
    startDate: "2026-11-04T10:00:00",
    endDate: "2026-11-05T18:00:00",
    organizer: "카카오",
    location: "코엑스 그랜드볼룸",
    isOnline: false,
    fee: 0,
    link: "https://if.kakao.com",
    description:
      "카카오의 연례 개발자 컨퍼런스. AI, 백엔드, 모바일, 인프라 등 100+ 세션.",
  },
  {
    source: "conf-it",
    externalId: "deview-2026",
    title: "NAVER DEVIEW 2026",
    category: "IT",
    type: "CONFERENCE",
    startDate: "2026-10-13T09:30:00",
    endDate: "2026-10-14T18:00:00",
    organizer: "네이버",
    location: "그랜드 인터컨티넨탈 서울",
    isOnline: false,
    fee: 0,
    link: "https://deview.kr",
    description:
      "네이버의 연례 기술 컨퍼런스. 검색, AI, 클라우드, 데이터, 인프라 등 핵심 트랙.",
  },
  {
    source: "conf-it",
    externalId: "woowacon-2026",
    title: "우아콘 2026",
    category: "IT",
    type: "CONFERENCE",
    startDate: "2026-11-12T10:00:00",
    endDate: "2026-11-12T18:00:00",
    organizer: "우아한형제들",
    location: "잠실 롯데호텔월드",
    isOnline: false,
    fee: 0,
    link: "https://woowacon.com",
    description:
      "배달의민족을 만드는 우아한형제들의 기술 컨퍼런스. 백엔드, 프론트엔드, 모바일, AI/ML.",
  },
  {
    source: "conf-it",
    externalId: "toss-slash-2026",
    title: "토스 SLASH 2026",
    category: "IT",
    type: "CONFERENCE",
    startDate: "2026-09-10T10:00:00",
    endDate: "2026-09-11T18:00:00",
    organizer: "토스 (Viva Republica)",
    location: "강남 SETEC",
    isOnline: false,
    fee: 0,
    link: "https://toss.tech/slash",
    description:
      "토스의 연례 기술 컨퍼런스. 금융 도메인의 대규모 트래픽/안정성/프로덕트 엔지니어링 사례.",
  },
  {
    source: "conf-it",
    externalId: "aws-summit-seoul-2026",
    title: "AWS Summit Seoul 2026",
    category: "IT",
    type: "CONFERENCE",
    startDate: "2026-05-14T09:00:00",
    endDate: "2026-05-15T18:00:00",
    organizer: "Amazon Web Services",
    location: "코엑스",
    isOnline: false,
    fee: 0,
    link: "https://aws.amazon.com/events/summits/seoul",
    description:
      "AWS의 연례 클라우드 컨퍼런스. 100+ 세션과 핸즈온 워크샵, 채용 부스 운영.",
  },
  {
    source: "conf-it",
    externalId: "google-io-extended-seoul-2026",
    title: "Google I/O Extended Seoul 2026",
    category: "IT",
    type: "CONFERENCE",
    startDate: "2026-05-25T18:30:00",
    endDate: "2026-05-25T22:00:00",
    organizer: "GDG Seoul",
    location: "구글 스타트업 캠퍼스",
    isOnline: false,
    fee: 0,
    link: "https://gdg.community.dev",
    description:
      "Google I/O 발표 내용을 한국에서 다시 풀어보는 커뮤니티 행사. Gemini, Android, Web 트랙.",
  },
  {
    source: "conf-it",
    externalId: "pycon-kr-2026",
    title: "PyCon Korea 2026",
    category: "IT",
    type: "CONFERENCE",
    startDate: "2026-08-01T10:00:00",
    endDate: "2026-08-02T18:00:00",
    organizer: "파이콘 한국 준비위원회",
    location: "성수 SETEC",
    isOnline: false,
    fee: 45000,
    link: "https://www.pycon.kr",
    description:
      "한국 파이썬 커뮤니티의 연례 컨퍼런스. 데이터, 웹, ML, 오픈소스 트랙.",
  },
  {
    source: "conf-it",
    externalId: "jsconf-kr-2026",
    title: "JSConf Korea 2026",
    category: "IT",
    type: "CONFERENCE",
    startDate: "2026-09-26T09:30:00",
    endDate: "2026-09-26T18:00:00",
    organizer: "JSConf Korea",
    location: "건국대학교 새천년관",
    isOnline: false,
    fee: 50000,
    link: "https://2026.jsconf.kr",
    description:
      "자바스크립트/타입스크립트 생태계 전반을 다루는 커뮤니티 컨퍼런스.",
  },
  {
    source: "conf-it",
    externalId: "samsung-sdc-2026",
    title: "Samsung Developer Conference Korea 2026",
    category: "IT",
    type: "CONFERENCE",
    startDate: "2026-11-19T10:00:00",
    endDate: "2026-11-19T18:00:00",
    organizer: "삼성전자",
    location: "코엑스",
    isOnline: false,
    fee: 0,
    link: "https://developer.samsung.com/sdc",
    description:
      "삼성 개발자 컨퍼런스 한국 에디션. Tizen, Bixby, IoT, Galaxy 플랫폼 세션.",
  },
  {
    source: "conf-it",
    externalId: "line-devday-2026",
    title: "LINE Developer Day 2026",
    category: "IT",
    type: "CONFERENCE",
    startDate: "2026-11-25T10:00:00",
    endDate: "2026-11-26T18:00:00",
    organizer: "LINE",
    location: "온라인",
    isOnline: true,
    fee: 0,
    link: "https://linedevday.linecorp.com",
    description:
      "LINE의 연례 글로벌 개발자 컨퍼런스. 한국에서도 온라인 참여 가능.",
  },
];
